SparkBank/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = "home"),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Change Site Title, Index Title and Site Title
admin.site.site_header = "Spark Bank Administration"
admin.site.site_title = "Spark Bank Administration"
admin.site.index_title = "Welcome to Spark Bank Administration Admin Panel"

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

admins/urls.py
from django.conf.urls import url
from . import views

app_name = "admins"

urlpatterns = [
    url(r"^$", views.index, name = "admin_index"),
]

profiles/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "profiles"

urlpatterns = [
    url(r"^account_status/$", views.index, name = "account_status"),
    url(r"^money_transfer/", views.money_transfer, name = "money_transfer"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

admins/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models
import datetime

class BasicDetails(models.Model):
    # (Name, Sex, DOB, Annual income, Email, Mobile number, Occupation) 
    name = models.CharField(max_length = 50, default = None)
    sex = models.CharField(max_length = 1, default = None)
    annual_income = models.IntegerField(default = 0)
    email = models.EmailField(default = None)
    mobile = models.IntegerField(default = 0)
    occupation = models.CharField(max_length = 50, default = None)
    DOB = models.DateField(default = None)
    user_name = models.CharField(max_length = 150, default = None)

class PresentLocation(models.Model):
    # (Country, State, City, Street, Pincode) 
    country = models.CharField(max_length = 50, default = "India")
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    street = models.CharField(max_length = 50)
    pincode = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class Status(models.Model):
    account_number = models.IntegerField()
    balance = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class MoneyTransfer(models.Model):
    enter_your_user_name = models.CharField(max_length = 150, default = None)
    enter_the_destination_account_number = models.IntegerField()
    enter_the_amount_to_be_transferred_in_INR = models.IntegerField()

profiles/forms.py
from django import forms
from . import models

class BasicDetailsForm (forms.ModelForm):
    # class to store all the model form fields from models.py
    class Meta:
        model = models.BasicDetails
        fields = ["name", "sex", "DOB", "annual_income", "email", "mobile", "occupation"]


class PresentLocationForm (forms.ModelForm):
    class Meta:
        model = models.PresentLocation
        fields = ["country", "state", "city", "street", "pincode"]

class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.MoneyTransfer
        fields = [
            "enter_your_user_name",
            "enter_the_destination_account_number", 
            "enter_the_amount_to_be_transferred_in_INR"
        ]

SparkBank/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index.html")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:signin")
    else:
        form = UserCreationForm()
    return render(request, "accounts/create_account.html", {"form": form})

def sign_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("profiles:account_status")
    else:
        form = AuthenticationForm()
        return render(request, "accounts/sign_in.html", {"form": form})

def logout_view(request):
    # Logout the user if he hits the logout submit button
    logout(request)
    return redirect("accounts:signin")

admins/views.py
from django.shortcuts import render

def index(request):
    return render(request, "admins/admin.html")

profiles/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from profiles.models import Status 
import random

def randomGen():
    # return a 6 digit random number
    return int(random.uniform(100000, 999999))

def index(request):
    try:
        curr_user = Status.objects.get(user_name=request.user) # getting details of current user
    except:
        # if no details exist (new user), create new details
        curr_user = Status()
        curr_user.account_number = randomGen() # random account number for every new user
        curr_user.balance = 0
        curr_user.user_name = request.user
        curr_user.save()
    return render(request, "profiles/profile.html", {"curr_user": curr_user})

def money_transfer(request):
    if request.method == "POST":
        form = forms.MoneyTransferForm(request.POST)
        if form.is_valid():
            form.save()
        
            curr_user = models.MoneyTransfer.objects.filter(enter_your_user_name=request.user)[0]
            dest_user_acc_num = curr_user.enter_the_destination_account_number

            temp = curr_user # NOTE: Delete this instance once money transfer is done
            
            dest_user = models.Status.objects.get(account_number=dest_user_acc_num) # FIELD 1
            transfer_amount = curr_user.enter_the_amount_to_be_transferred_in_INR # FIELD 2
            curr_user = models.Status.objects.get(user_name=request.user) # FIELD 3

            # Now transfer the money!
            curr_user.balance = curr_user.balance - transfer_amount
            dest_user.balance = dest_user.balance + transfer_amount

            # Save the changes before redirecting
            curr_user.save()
            dest_user.save()

            temp.delete() #  Now deleting the instance for future money transactions

        return redirect("profiles/profile.html")
    else:
        form = forms.MoneyTransferForm()
    return render(request, "profiles/money_transfer.html", {"form": form})

accounts/templates/accounts/create_account.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Slabo+27px');

    .navigation {
        height: 70px;
        background: #262626;
    }

    body {
        background-color: DodgerBlue;
    }

    .brand {
        position: absolute;
        padding-left: 20px;
        float: left;
        line-height: 70px;
        text-transform: uppercase;
        font-size: 1.4em;
    }

    .brand a,
    .brand a:visited {
        color: #fff;
        text-decoration: none;
    }

    .nav-container {
        max-width: 1000px;
        margin: 0 auto;
    }

    nav {
        float: right;
    }

    nav ul {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    nav ul li {
        float: left;
        position: relative;
    }

    nav ul li a,
    nav ul li a:visited {
        display: block;
        padding: 0 20px;
        line-height: 70px;
        background: #262626;
        color: #fff;
        text-decoration: none;
    }

    nav ul li a:hover,
    nav ul li a:visited:hover {
        background: #2581dc;
        color: #fff;
        text-decoration: none;
    }

    nav ul li a:not(:only-child):after,
    nav ul li a:visited:not(:only-child):after {
        padding-left: 4px;
        content: " ▾";
    }

    nav ul li ul li {
        min-width: 190px;
    }

    nav ul li ul li a {
        padding: 15px;
        line-height: 20px;
    }

    .nav-dropdown {
        position: absolute;
        display: none;
        z-index: 1;
        box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
    }

    /* Mobile navigation */
    .nav-mobile {
        display: none;
        position: absolute;
        top: 0;
        right: 0;
        background: #262626;
        height: 70px;
        width: 70px;
    }

    @media only screen and (max-width: 798px) {
        .nav-mobile {
            display: block;
        }

        nav {
            width: 100%;
            padding: 70px 0 15px;
        }

        nav ul {
            display: none;
        }

        nav ul li {
            float: none;
        }

        nav ul li a {
            padding: 15px;
            line-height: 20px;
        }

        nav ul li ul li a {
            padding-left: 30px;
        }

        .nav-dropdown {
            position: static;
        }
    }

    @media screen and (min-width: 799px) {
        .nav-list {
            display: block !important;
        }
    }

    #nav-toggle {
        position: absolute;
        left: 18px;
        top: 22px;
        cursor: pointer;
        padding: 10px 35px 16px 0px;
    }

    #nav-toggle span,
    #nav-toggle span:before,
    #nav-toggle span:after {
        cursor: pointer;
        border-radius: 1px;
        height: 5px;
        width: 35px;
        background: #fff;
        position: absolute;
        display: block;
        content: "";
        transition: all 300ms ease-in-out;
    }

    #nav-toggle span:before {
        top: -10px;
    }

    #nav-toggle span:after {
        bottom: -10px;
    }

    #nav-toggle.active span {
        background-color: transparent;
    }

    #nav-toggle.active span:before,
    #nav-toggle.active span:after {
        top: 0;
    }

    #nav-toggle.active span:before {
        transform: rotate(45deg);
    }

    #nav-toggle.active span:after {
        transform: rotate(-45deg);
    }

    article {
        max-width: 1000px;
        margin: 0 auto;
        padding: 10px;
    }



    h2 {
        font-family: 'Slabo 27px';
        border-bottom: 1px solid black;
        font-weight: 900;
    }

    form ul {
        list-style: none;
    }

    .foot {
        position: absolute;
        bottom: 0px;
        left: 0px;
        right: 0px;
    }
</style>


<script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}


{% block bodycontent %}
<h2 class="container text-center">Create New Account</h2>
<h6 class="text-center"><em>(All details are mandatory)</em></h6>
<br>

<form class="container" action="/accounts/register/" method="post">
    {% csrf_token %}
    <section class="form-control">
        <h4>Enter basic details</h4>
        {{ form }}
    </section>
    <br>
    <br>

    <section>
        <input type="checkbox" required>
        <small>By clicking "Create account" you agree to our
            <a href="#">Terms and Conditions</a>.</small>
    </section>

    <br>

    <input type="submit" class="form-control btn btn-danger" value="Create account" name="submit" />

</form>

<br>
{% endblock %}

{% block scriptcontent %}
<script>
    $(".active").removeClass("active");
    $("#nav-create").addClass("active");

    $(".helptext").html("");

    var input_text = $("input[type=text]");
    input_text.addClass("form-control");

    var input_pass = $("input[type=password]");
    input_pass.addClass("form-control");

    $("form ul li").addClass("btn btn-danger");

</script>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
<style>
    .navigation {
        height: 70px;
        background: #262626;
    }

    .brand {
        position: absolute;
        padding-left: 20px;
        float: left;
        line-height: 70px;
        text-transform: uppercase;
        font-size: 1.4em;
    }

    .brand a,
    .brand a:visited {
        color: #fff;
        text-decoration: none;
    }

    .nav-container {
        max-width: 1000px;
        margin: 0 auto;
    }

    nav {
        float: right;
    }

    nav ul {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    nav ul li {
        float: left;
        position: relative;
    }

    nav ul li a,
    nav ul li a:visited {
        display: block;
        padding: 0 20px;
        line-height: 70px;
        background: #262626;
        color: #fff;
        text-decoration: none;
    }

    nav ul li a:hover,
    nav ul li a:visited:hover {
        background: #2581dc;
        color: #fff;
        text-decoration: none;
    }

    nav ul li a:not(:only-child):after,
    nav ul li a:visited:not(:only-child):after {
        padding-left: 4px;
        content: " ▾";
    }

    nav ul li ul li {
        min-width: 190px;
    }

    nav ul li ul li a {
        padding: 15px;
        line-height: 20px;
    }

    .nav-dropdown {
        position: absolute;
        display: none;
        z-index: 1;
        box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
    }

    /* Mobile navigation */
    .nav-mobile {
        display: none;
        position: absolute;
        top: 0;
        right: 0;
        background: #262626;
        height: 70px;
        width: 70px;
    }

    @media only screen and (max-width: 798px) {
        .nav-mobile {
            display: block;
        }

        nav {
            width: 100%;
            padding: 70px 0 15px;
        }

        nav ul {
            display: none;
        }

        nav ul li {
            float: none;
        }

        nav ul li a {
            padding: 15px;
            line-height: 20px;
        }

        nav ul li ul li a {
            padding-left: 30px;
        }

        .nav-dropdown {
            position: static;
        }
    }

    @media screen and (min-width: 799px) {
        .nav-list {
            display: block !important;
        }
    }

    #nav-toggle {
        position: absolute;
        left: 18px;
        top: 22px;
        cursor: pointer;
        padding: 10px 35px 16px 0px;
    }

    #nav-toggle span,
    #nav-toggle span:before,
    #nav-toggle span:after {
        cursor: pointer;
        border-radius: 1px;
        height: 5px;
        width: 35px;
        background: #fff;
        position: absolute;
        display: block;
        content: "";
        transition: all 300ms ease-in-out;
    }

    #nav-toggle span:before {
        top: -10px;
    }

    #nav-toggle span:after {
        bottom: -10px;
    }

    #nav-toggle.active span {
        background-color: transparent;
    }

    #nav-toggle.active span:before,
    #nav-toggle.active span:after {
        top: 0;
    }

    #nav-toggle.active span:before {
        transform: rotate(45deg);
    }

    #nav-toggle.active span:after {
        transform: rotate(-45deg);
    }

    article {
        max-width: 1000px;
        margin: 0 auto;
        padding: 10px;
    }

    body {
        background-color: DodgerBlue;
    }

    .foot {
        position: absolute;
        bottom: 0px;
        left: 0px;
        right: 0px;
    }
</style>
{% endblock %}


{% block bodycontent%}
<h2 class="container text-center">Login to your Account</h2>

<div style=" margin-top: 50px;" class="container bg-info">
    <form class="form-control" action="/accounts/login/" method="post">
        {% csrf_token %}
        <h2>Enter login details</h2>

        {{ form }}

        <br>

        <button type="submit" class="btn btn-success">
            <i class="fa fa-sign-in"></i>
            Login
        </button>

        <br> <br>

        <small class="row">

            <a href="{% url 'accounts:signup' %}" class="col text-right">Create New Account</a>
        </small>
    </form>
</div>

{% endblock %}

{% block scriptcontent %}
<script>
    $(".active").removeClass("active");
    $("#nav-login").addClass("active");
    $("input").addClass("form-control");
</script>
{% endblock %}

profiles/templates/profiles/money_transfer.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
<style>
    @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');

    body {
        background-color: floralwhite;
    }

    h2 {
        font-family: "PT Serif";
    }

    #side_panel {
        font-size: 16px;
        font-family: "Titillium Web";
        background-color: rgb(170, 95, 57);
        margin-top: -7px;
        margin-left: -10px;
        height: 540px;
        overflow-x: auto;
        overflow-y: auto;
    }

    .side {
        color: aliceblue;
    }

    .side:hover {
        color: mediumaquamarine;
    }

    .warning {
        color: yellow;
    }

    .danger {
        color: #FF8723;
        font-weight: 900;
    }

    .current {
        border: 1px solid;
        padding: 3px;
    }

    .curr_bal {
        font-family: "Cinzel";
        font-weight: 600;
    }

    #side_panel::-webkit-scrollbar {
        width: 7px;
    }

    #side_panel::-webkit-scrollbar:hover {
        width: 12px;
    }

    #side_panel::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 3px rgba(0, 0, 0, 0.3);
        border-radius: 10px;
    }

    ::-webkit-scrollbar-thumb {
        border-radius: 10px;
        -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.5);
    }
</style>
{% endblock %}

{% block bodycontent %}
<section style="margin-left: 10em; margin-top: 50px;" id="welcome_post" class="col-9">
    <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
    <h4 style="font-weight: 300;">It's good to have you here.</h4>

    <form action="{% url 'profiles:money_transfer' %}" method="post">
        {% block content %}
        {% csrf_token %}
        {% endblock %}
        <h3 style="font-weight: 300;">
            {{ form }}
        </h3>

        <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount
            transfer</small>. <br>
        <button type="submit" class="btn btn-danger">Transfer amount</button>
    </form>
</section>
{% endblock %}

{% block scriptcontent %}
<script>
    $(".current").removeClass("current");
    $("#transfer").addClass("current");

    $("input").addClass("form-control");
    $("label").prepend("<br>")
</script>
{% endblock %}

profiles/templates/profiles/profile_base_layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Myrel Bank | Profile</title>

    <!-- CSS FRAMEWORKS REQUIRED -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
        integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="../static/js/script.js"></script>
    <!-- STYLINGS -->
    <style>
        .navigation {
            height: 70px;
            background: #262626;
        }

        body {
            background-color: DodgerBlue;
        }

        .brand {
            position: absolute;
            padding-left: 20px;
            float: left;
            line-height: 70px;
            text-transform: uppercase;
            font-size: 1.4em;
        }

        .brand a,
        .brand a:visited {
            color: #fff;
            text-decoration: none;
        }

        .nav-container {
            max-width: 1000px;
            margin: 0 auto;
        }

        nav {
            float: right;
        }

        nav ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        nav ul li {
            float: left;
            position: relative;
        }

        nav ul li a,
        nav ul li a:visited {
            display: block;
            padding: 0 20px;
            line-height: 70px;
            background: #262626;
            color: #fff;
            text-decoration: none;
        }

        nav ul li a:hover,
        nav ul li a:visited:hover {
            background: #2581dc;
            color: #fff;
            text-decoration: none;
        }

        nav ul li a:not(:only-child):after,
        nav ul li a:visited:not(:only-child):after {
            padding-left: 4px;
            content: " ▾";
        }

        nav ul li ul li {
            min-width: 190px;
        }

        nav ul li ul li a {
            padding: 15px;
            line-height: 20px;
        }

        .nav-dropdown {
            position: absolute;
            display: none;
            z-index: 1;
            box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
        }

        /* Mobile navigation */
        .nav-mobile {
            display: none;
            position: absolute;
            top: 0;
            right: 0;
            background: #262626;
            height: 70px;
            width: 70px;
        }

        @media only screen and (max-width: 798px) {
            .nav-mobile {
                display: block;
            }

            nav {
                width: 100%;
                padding: 70px 0 15px;
            }

            nav ul {
                display: none;
            }

            nav ul li {
                float: none;
            }

            nav ul li a {
                padding: 15px;
                line-height: 20px;
            }

            nav ul li ul li a {
                padding-left: 30px;
            }

            .nav-dropdown {
                position: static;
            }
        }

        @media screen and (min-width: 799px) {
            .nav-list {
                display: block !important;
            }
        }

        #nav-toggle {
            position: absolute;
            left: 18px;
            top: 22px;
            cursor: pointer;
            padding: 10px 35px 16px 0px;
        }

        #nav-toggle span,
        #nav-toggle span:before,
        #nav-toggle span:after {
            cursor: pointer;
            border-radius: 1px;
            height: 5px;
            width: 35px;
            background: #fff;
            position: absolute;
            display: block;
            content: "";
            transition: all 300ms ease-in-out;
        }

        #nav-toggle span:before {
            top: -10px;
        }

        #nav-toggle span:after {
            bottom: -10px;
        }

        #nav-toggle.active span {
            background-color: transparent;
        }

        #nav-toggle.active span:before,
        #nav-toggle.active span:after {
            top: 0;
        }

        #nav-toggle.active span:before {
            transform: rotate(45deg);
        }

        #nav-toggle.active span:after {
            transform: rotate(-45deg);
        }

        article {
            max-width: 1000px;
            margin: 0 auto;
            padding: 10px;
        }

        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }

        form ul {
            list-style: none;
        }

        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>


    {% block headcontent %}
    {% endblock %}

</head>

<body>
    <section class="navigation">
        <div class="nav-container">
            <div class="brand">
                <a href="{% url 'home' %}">Spark Bank</a>
            </div>
            <nav>
                <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'profiles:account_status' %}">Account status</a>
                    </li>
                    <li>
                        <a href="{% url 'profiles:money_transfer' %}">Money Transfer</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    </li>
                </ul>
            </nav>
        </div>
    </section>

    <div class="container-fluid row">


        {% block bodycontent %}
        {% endblock %}

    </div>

    <!-- FOOTER -->

    <!-- JS LIBRARIES REQUIRED -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

    {% block scriptcontent %}
    {% endblock %}
</body>

</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Spark Bank</title>

    <!-- CSS FRAMEWORKS REQUIRED -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
        integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- JS File -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="../static/js/script.js"></script>

    {% block stylecontent %}

    {% endblock %}

    <link rel="stylesheet" href="/static/css/common-styles.css">

</head>

<body>
    <section class="navigation">
        <div class="nav-container">
            <div class="brand">
                <a href="{% url 'home' %}">Spark Bank</a>
            </div>
            <nav>
                <div class="nav-mobile"><a id="nav-toggle" href="#"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:signup' %}">Create new account</a>
                    </li>

                    <li>
                        <a href="{% url 'accounts:signin' %}"> Sign In </a>

                </ul>
            </nav>
        </div>
    </section>
    {% block bodycontent %}

    {% endblock %}

    <!-- FOOTER -->
    <section style="background-color: #262626;" class="foot text-white">
        <div class="text-center">
            &copy; Created by Sharath
        </div>
    </section>

    <!-- JS LIBRARIES REQUIRED -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

    {% block scriptcontent %}
    {% endblock %}

</body>

</html>

templates/index.html
{% extends 'base_layout.html' %}
{% load static %}

{% block stylecontent %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
    body {
        background-image: url(../static/images/bankbgc.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
</style>
{% endblock %}


{% block bodycontent %}
<h1 class="container text-center">Welcome to Spark Bank!</h1>
{% endblock %}